# Generated by Django 5.2.6 on 2025-09-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ci', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=40)),
                ('apPaterno', models.CharField(max_length=35)),
                ('apMaterno', models.CharField(blank=True, max_length=35)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=10)),
                ('idResidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.tipovehiculo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.marcavehiculo')),
            ],
        ),
    ]
