# Generated by Django 5.2.6 on 2025-09-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcavehiculo',
            old_name='nombre',
            new_name='marca',
        ),
    ]
