# Generated by Django 5.2.6 on 2025-09-12 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_rename_nombre_marcavehiculo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Ingrese un número (solo dígitos).', max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo solo admite números.', 'invalid_number')])),
                ('idResidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
            ],
        ),
    ]
