# Generated by Django 5.2.6 on 2025-09-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0003_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='idResidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residentes.residente'),
        ),
    ]
