# Generated by Django 5.2.6 on 2025-09-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0004_alter_telefono_idresidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='residente',
            name='estado',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='residente',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residente',
            name='tipo',
            field=models.CharField(choices=[('P', 'Propietario'), ('I', 'Inquilino')], default='P', max_length=1),
        ),
    ]
