# Generated by Django 5.2.6 on 2025-09-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_tipopropiedad'),
        ('residentes', '0005_residente_email_residente_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='idPropiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad'),
        ),
    ]
