# Generated by Django 5.2.6 on 2025-09-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('hora_fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('id_accion', models.IntegerField(blank=True, null=True)),
                ('accion_realizada', models.CharField(max_length=255)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-hora_fecha_ingreso'],
            },
        ),
    ]
