# Generated by Django 5.2.6 on 2025-09-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={},
        ),
    ]
