# Generated by Django 5.2.6 on 2025-09-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_bitacora_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='hora_fecha_ingreso',
            new_name='hora_fecha',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='hora_fecha_salida',
        ),
    ]
