# Generated by Django 5.2.6 on 2025-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.CharField(help_text='Número o identificador único de la propiedad (ej. A-101, Torre B-205).', max_length=10, unique=True, verbose_name='Número de Unidad')),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Una descripción detallada de la propiedad.', null=True)),
                ('habitada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['numero_unidad'],
            },
        ),
    ]
