# Generated by Django 5.2.6 on 2025-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(help_text='Indique una dirección (ej. Calle Yotaú # 12).', max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitada',
            field=models.BooleanField(default=False, help_text='Tickear si la propiedad está habitada'),
        ),
    ]
