# Generated by Django 5.2.6 on 2025-09-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_direccion_alter_propiedad_habitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipoPropiedad',
            field=models.CharField(choices=[('V', 'Vivienda'), ('C', 'Comercial')], default='V', max_length=1),
        ),
    ]
