# Generated by Django 5.2.6 on 2025-09-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_tipopropiedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='tipoPropiedad',
            new_name='tipo_propiedad',
        ),
    ]
